-- MySQL Script generated by MySQL Workbench
-- Tue Apr 26 21:02:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema unidad2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema unidad2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unidad2` DEFAULT CHARACTER SET utf8 ;
USE `unidad2` ;

-- -----------------------------------------------------
-- Table `unidad2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad2`.`usuario` (
  `Codigo` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(15) NULL,
  `Clave` VARCHAR(45) NULL,
  `EstaActivo` TINYINT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unidad2`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad2`.`producto` (
  `Codigo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Precio` DECIMAL(18,2) NULL,
  `Existencia` INT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unidad2`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad2`.`pedido` (
  `Codigo` VARCHAR(45) NOT NULL,
  `Cliente` VARCHAR(45) NULL,
  `Total` DECIMAL NULL,
  `IdProducto` VARCHAR(45) NULL,
  `Cantidad` INT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `FK_pedido_producto_idx` (`IdProducto` ASC) VISIBLE,
  CONSTRAINT `FK_pedido_producto`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `unidad2`.`producto` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
